import {
  Automatic,
  Bed,
  CD,
  Freezer,
  Gas,
  Kitchen,
  Microwave,
  Paper,
  Radio,
  Screen,
  Shower,
  Hob,
  Water,
  Bathroom,
  Wind,
  Conditioner,
} from 'components/Icons';

export const iconDetails = {
  automatic: <Automatic />,
  airConditioner: <Conditioner />,
  AC: <Wind />,
  toilet: <Paper />,
  CD: <CD />,
  TV: <Screen />,
  kitchen: <Kitchen />,
  beds: <Bed />,
  radio: <Radio />,
  shower: <Shower />,
  freezer: <Freezer />,
  microwave: <Microwave />,
  gas: <Gas />,
  water: <Water />,
  hob: <Hob />,
  bathroom: <Bathroom />,
};
